### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by alex-jvv-saltpay**

### CODE REVIEW

**Comment by alex-jvv-saltpay** [comment]
atlantis plan

**Comment by alex-jvv-saltpay** [comment]
atlantis plan

**Comment by alex-jvv-saltpay** [comment]
atlantis plan

**Comment by yoyo-atlantis** [comment]
Ran Plan for dir: `test` workspace: `default`

**Plan Error**
```
exit status 1: running "terragrunt plan -no-color -out $PLANFILE $COMMENT_ARG" in "/home/atlantis/.atlantis/repos/alex-jvv-saltpay/atlantis-pr-test/1/default/test": 
time=2023-03-13T03:58:33Z level=error msg=Error reading file at path /home/atlantis/.atlantis/repos/alex-jvv-saltpay/atlantis-pr-test/1/default/test/terragrunt.hcl: open /home/atlantis/.atlantis/repos/alex-jvv-saltpay/atlantis-pr-test/1/default/test/terragrunt.hcl: no such file or directory
time=2023-03-13T03:58:33Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1


```

**Comment by alex-jvv-saltpay** [comment]
Not terragrunt

**Pull request closed without merging**
